### ISSUE TITLE
App can not be accessed in docker container

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Genie.jl#331]
Per feedback in Gitter

**Comment by NLaws** [comment]
is this fixable by adding an ingress layer (such as Nginx)? I have been trying to use the [basic json example](https://genieframework.github.io/Genie.jl/dev/tutorials/7--Using_JSON_Payloads.html#Example) in a container but have not been able to access the Genie port from the host.

From the `docker-compose.yml`:
```
...

  julia:
    container_name: julia_api
    build:
      context: .
    command: julia --project="/opt/julia_src" api.jl
    ports:
      - "8081:8081"
```
and `api.jl`:
```
using Genie, Genie.Router, Genie.Requests, Genie.Renderer.Json
include("REopt.jl")
using .REopt

Genie.config.run_as_server = true

route("/jsonpayload", method = POST) do
  data = jsonpayload() # Dict{String,Any}
  results = reopt(data)
  json(results)
end

Genie.startup(8081)
```
